import type { TerminalLine, DomainNode, DomainEdge } from "./types"

export const RECON_MODULES = [
  {
    category: "recon",
    modules: [
      { path: "recon/domains-hosts/bing_domain_web", name: "Bing Domain Search", description: "Searches Bing for sub-domains" },
      { path: "recon/domains-hosts/brute_hosts", name: "DNS Brute Forcer", description: "Brute forces host names using DNS" },
      { path: "recon/domains-hosts/google_site_web", name: "Google Site Search", description: "Searches Google for sub-domains" },
      { path: "recon/domains-hosts/hackertarget", name: "HackerTarget Lookup", description: "Uses HackerTarget API for host lookups" },
      { path: "recon/domains-hosts/ssl_san", name: "SSL SAN Lookup", description: "Uses SSL certificates to find sub-domains via SAN" },
      { path: "recon/domains-hosts/threatcrowd", name: "ThreatCrowd DNS", description: "Leverages ThreatCrowd passive DNS data" },
      { path: "recon/domains-contacts/whois_pocs", name: "Whois POC Lookup", description: "Uses WHOIS to find domain contacts" },
      { path: "recon/hosts-hosts/resolve", name: "Hostname Resolver", description: "Resolves the IP address for a host" },
      { path: "recon/netblocks-hosts/shodan_net", name: "Shodan Net Lookup", description: "Leverages Shodan for host discovery in netblocks" },
      { path: "recon/hosts-ports/shodan_ip", name: "Shodan IP Lookup", description: "Leverages Shodan to discover open ports" },
      { path: "recon/contacts-credentials/hibp_breach", name: "HIBP Breach Search", description: "Searches HIBP for breached credentials" },
      { path: "recon/contacts-credentials/hibp_paste", name: "HIBP Paste Search", description: "Searches HIBP for pasted credentials" },
    ],
  },
  {
    category: "discovery",
    modules: [
      { path: "discovery/info_disclosure/cache_snoop", name: "DNS Cache Snooper", description: "Checks for DNS cache snooping" },
      { path: "discovery/info_disclosure/interesting_files", name: "Interesting Files", description: "Discovers interesting files on target hosts" },
    ],
  },
  {
    category: "import",
    modules: [
      { path: "import/csv_file", name: "CSV File Import", description: "Imports data from a CSV file" },
      { path: "import/list", name: "List Import", description: "Imports data from a list" },
      { path: "import/nmap", name: "Nmap XML Import", description: "Imports hosts from Nmap XML output" },
    ],
  },
  {
    category: "reporting",
    modules: [
      { path: "reporting/csv", name: "CSV Reporter", description: "Creates a CSV report" },
      { path: "reporting/html", name: "HTML Reporter", description: "Creates an HTML report" },
      { path: "reporting/json", name: "JSON Reporter", description: "Creates a JSON report" },
      { path: "reporting/xlsx", name: "XLSX Reporter", description: "Creates an XLSX report" },
      { path: "reporting/pushpin", name: "Pushpin Reporter", description: "Creates a map-based report" },
    ],
  },
]

export const INITIAL_TERMINAL_LINES: TerminalLine[] = [
  { id: "1", type: "system", content: "  ____                                           ", timestamp: new Date() },
  { id: "2", type: "system", content: " |  _ \\ ___  ___ ___  _ __        _ __   __ _    ", timestamp: new Date() },
  { id: "3", type: "system", content: " | |_) / _ \\/ __/ _ \\| '_ \\ ___ | '_ \\ / _` |   ", timestamp: new Date() },
  { id: "4", type: "system", content: " |  _ <  __/ (_| (_) | | | |___|| | | | (_| |   ", timestamp: new Date() },
  { id: "5", type: "system", content: " |_| \\_\\___|\\___\\___/|_| |_|    |_| |_|\\__, |   ", timestamp: new Date() },
  { id: "6", type: "system", content: "                                       |___/     ", timestamp: new Date() },
  { id: "7", type: "system", content: "", timestamp: new Date() },
  { id: "8", type: "info", content: "[recon-ng v5.1.2, Tim Tomes (@lanmaster53)]", timestamp: new Date() },
  { id: "9", type: "system", content: "", timestamp: new Date() },
  { id: "10", type: "success", content: "[12] Recon modules", timestamp: new Date() },
  { id: "11", type: "success", content: "[ 2] Discovery modules", timestamp: new Date() },
  { id: "12", type: "success", content: "[ 3] Import modules", timestamp: new Date() },
  { id: "13", type: "success", content: "[ 5] Reporting modules", timestamp: new Date() },
  { id: "14", type: "system", content: "", timestamp: new Date() },
  { id: "15", type: "output", content: "[default] > ", timestamp: new Date() },
]

export const MOCK_DOMAINS: DomainNode[] = [
  { id: "d1", label: "example.com", type: "domain" },
  { id: "d2", label: "sub.example.com", type: "domain" },
  { id: "h1", label: "www.example.com", type: "host" },
  { id: "h2", label: "mail.example.com", type: "host" },
  { id: "h3", label: "api.example.com", type: "host" },
  { id: "h4", label: "cdn.example.com", type: "host" },
  { id: "h5", label: "dev.example.com", type: "host" },
  { id: "h6", label: "staging.example.com", type: "host" },
  { id: "h7", label: "admin.example.com", type: "host" },
  { id: "ip1", label: "93.184.216.34", type: "ip" },
  { id: "ip2", label: "93.184.216.35", type: "ip" },
  { id: "ip3", label: "104.26.10.78", type: "ip" },
  { id: "ip4", label: "172.67.74.152", type: "ip" },
  { id: "ip5", label: "93.184.216.40", type: "ip" },
  { id: "n1", label: "93.184.216.0/24", type: "netblock" },
]

export const MOCK_EDGES: DomainEdge[] = [
  { source: "d1", target: "h1", label: "A" },
  { source: "d1", target: "h2", label: "MX" },
  { source: "d1", target: "h3", label: "A" },
  { source: "d1", target: "h4", label: "CNAME" },
  { source: "d1", target: "h5", label: "A" },
  { source: "d1", target: "h6", label: "A" },
  { source: "d1", target: "h7", label: "A" },
  { source: "d2", target: "d1", label: "subdomain" },
  { source: "h1", target: "ip1", label: "resolves" },
  { source: "h2", target: "ip2", label: "resolves" },
  { source: "h3", target: "ip3", label: "resolves" },
  { source: "h4", target: "ip4", label: "resolves" },
  { source: "h5", target: "ip1", label: "resolves" },
  { source: "h6", target: "ip5", label: "resolves" },
  { source: "h7", target: "ip1", label: "resolves" },
  { source: "ip1", target: "n1", label: "belongs" },
  { source: "ip2", target: "n1", label: "belongs" },
  { source: "ip5", target: "n1", label: "belongs" },
]

export const TABLE_SUMMARY = [
  { name: "domains", count: 3 },
  { name: "hosts", count: 7 },
  { name: "contacts", count: 12 },
  { name: "credentials", count: 8 },
  { name: "companies", count: 2 },
  { name: "netblocks", count: 1 },
  { name: "ports", count: 24 },
  { name: "vulnerabilities", count: 5 },
  { name: "locations", count: 0 },
  { name: "profiles", count: 15 },
  { name: "repositories", count: 6 },
  { name: "leaks", count: 3 },
  { name: "pushpins", count: 0 },
]

export const COMMAND_RESPONSES: Record<string, { type: TerminalLine["type"]; lines: string[] }> = {
  help: {
    type: "output",
    lines: [
      "Commands (type [help|?] <topic>):",
      "-----------------------------------",
      "  dashboard       Displays a summary of activity",
      "  db              Interfaces with the workspace's database",
      "  exit            Exits the current context",
      "  help            Displays this menu",
      "  keys            Manages framework API keys",
      "  marketplace     Interfaces with the module marketplace",
      "  modules         Interfaces with installed modules",
      "  options         Manages the current context options",
      "  pdb             Starts a Python Debugger session",
      "  script          Records and executes command scripts",
      "  shell           Executes shell commands",
      "  show            Shows various framework items",
      "  snapshots       Manages workspace snapshots",
      "  spool           Spools output to a file",
      "  workspaces      Manages workspaces",
    ],
  },
  dashboard: {
    type: "output",
    lines: [
      "",
      "  +---------------------------------------------+",
      "  |              Module Summary                  |",
      "  +---------------------------------------------+",
      "  | recon/domains-hosts/brute_hosts       |   3  |",
      "  | recon/domains-hosts/google_site_web   |   2  |",
      "  | recon/hosts-hosts/resolve             |   5  |",
      "  | recon/netblocks-hosts/shodan_net      |   1  |",
      "  +---------------------------------------------+",
      "",
      "  +---------------------------------------------+",
      "  |              Record Summary                  |",
      "  +---------------------------------------------+",
      "  | ports              |  24                     |",
      "  | profiles           |  15                     |",
      "  | contacts           |  12                     |",
      "  | credentials        |   8                     |",
      "  | hosts              |   7                     |",
      "  | repositories       |   6                     |",
      "  | vulnerabilities    |   5                     |",
      "  | domains            |   3                     |",
      "  | leaks              |   3                     |",
      "  | companies          |   2                     |",
      "  | netblocks          |   1                     |",
      "  +---------------------------------------------+",
    ],
  },
  "show modules": {
    type: "output",
    lines: [
      "",
      "  Recon",
      "  -----",
      "    recon/domains-hosts/bing_domain_web",
      "    recon/domains-hosts/brute_hosts",
      "    recon/domains-hosts/google_site_web",
      "    recon/domains-hosts/hackertarget",
      "    recon/domains-hosts/ssl_san",
      "    recon/domains-hosts/threatcrowd",
      "    recon/domains-contacts/whois_pocs",
      "    recon/hosts-hosts/resolve",
      "    recon/netblocks-hosts/shodan_net",
      "    recon/hosts-ports/shodan_ip",
      "",
      "  Discovery",
      "  ---------",
      "    discovery/info_disclosure/cache_snoop",
      "    discovery/info_disclosure/interesting_files",
      "",
      "  Import",
      "  ------",
      "    import/csv_file",
      "    import/list",
      "    import/nmap",
      "",
      "  Reporting",
      "  ---------",
      "    reporting/csv",
      "    reporting/html",
      "    reporting/json",
      "    reporting/xlsx",
      "    reporting/pushpin",
    ],
  },
  "show tables": {
    type: "output",
    lines: [
      "",
      "  +-----------------+",
      "  |     Tables      |",
      "  +-----------------+",
      "  | companies       |",
      "  | contacts        |",
      "  | credentials     |",
      "  | domains         |",
      "  | hosts           |",
      "  | leaks           |",
      "  | locations       |",
      "  | netblocks       |",
      "  | ports           |",
      "  | profiles        |",
      "  | pushpins        |",
      "  | repositories    |",
      "  | vulnerabilities |",
      "  +-----------------+",
    ],
  },
}
